[package]
name = "epl-auth"
version = "1.0.0"
description = "First-party authentication and JWT library for EPL."
authors = ["Abneesh Singh"]
license = "MIT"
readme = "README.md"
main = "main.epl"

[dependencies]
# Standard library dependencies
epl-web = "^1.0.0"

[repository]
url = "https://github.com/abneeshsingh21/epl-auth"
